/*
 * This source file was generated by the Gradle 'init' task
 */
package com.MotorPh;

import Forms.LoginForm;
import Helper.Injector;

public class App {

  public static void main(String[] args) {
    LoginForm loginForm = Injector.CreateLoginForm();
    loginForm.setVisible(true);
  }
}
